

tags:
- name: "Products"
  description: "Everything about Products"


/products/:
  get:
   summary: "Get all products"
   operationId: "getProducts"
   consumes:
   - "application/json"
   tags:
   - "Products"

   responses:
    200:
      description: "products"
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              $ref: '#/components/schemas/Product'
        


/products/{id}/:
  get:
    summary: "Get one product by id"
    operationId: "getProduct"
    parameters:
    - name: "id"
      in: "path"
      description: "Product id"
      required: true
      type: "string"
    consumes:
    - "application/json"
    tags:
    - "Products"
    responses:
      200:
        description: "products"
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Product'
